description: symnet_2080ti_slots8
resources:
  agent_label: rtx2080ti
  slots: 8
bind_mounts:
  - host_path: /mnt/datasets/
    container_path: /home/public_datasets/
  - host_path: /mnt/u/linyongliang/
    container_path: /home/
  - host_path: /mnt/data/linbo/
    container_path: /home/local_datasets/
environment:
  image: lyltc1/symnet:1.0.0

# conda activate (where determined installed)
# det user login linyongliang
# det shell start --config-file config.yaml
# det shell list
# det shell show_ssh_command db8e4fb8-f18f-4c91-8a98-6c5e650f13e8
# det shell kill db8e4fb8-f18f-4c91-8a98-6c5e650f13e8
# tmux
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python core/symn/run_train.py --config-file configs/symn/ycbv/symn_ycbv_config_bit16_pbr.py --gpus 0 1 2 3 4 5 6 7 --obj_id 21