description: symnet_2080ti_slots4
resources:
  agent_label: rtx2080ti
  slots: 4
bind_mounts:
  - host_path: /mnt/datasets/
    container_path: /home/public_datasets/
  - host_path: /mnt/u/linyongliang/
    container_path: /home/
  - host_path: /mnt/data/linbo/
    container_path: /home/local_datasets/
environment:
  image: lyltc1/symnet:1.0.0

# conda activate (where determined installed)
# det user login linyongliang
# det shell start --config-file config.yaml
# det shell list
# det shell show_ssh_command 60ae5e06-0bc0-4f7e-8bc8-4caf32e2296e
# det shell kill 60ae5e06-0bc0-4f7e-8bc8-4caf32e2296e
